export const ARTICLES_LOADED = 'ARTICLES_LOADED';
export const CURRENT_ARTICLE_LOADED = 'CURRENT_ARTICLE_LOADED';

export const AUTHORIZED = 'AUTHORIZED';

export const SHOW_ALL = 'SHOW_ALL';
export const SHOW_MY = 'SHOW_MY';

export const CURRENT_USER_PROFILE_LOAD = 'CURRENT_USER_PROFILE_LOAD';

export const SET_CURRENT_MENU_ITEM = 'SET_CURRENT_MENU_ITEM';
