export const ARTICLES_LOAD = 'ARTICLES_LOAD';
export const SET_FILTER_BY_AUTHOR = 'SET_FILTER_BY_AUTHOR';

export const SET_AUTHORIZED = 'SET_AUTHORIZED';
export const CURRENT_USER_PROFILE_LOAD = 'CURRENT_USER_PROFILE_LOAD';

export const SET_CURRENT_MENU_ITEM = 'SET_CURRENT_MENU_ITEM';
