export const ARTICLES_LOADED = 'ARTICLES_LOADED';
export const CURRENT_ARTICLE_LOADED = 'CURRENT_ARTICLE_LOADED';

export const SET_AUTHORIZED = 'SET_AUTHORIZED';

export const SHOW_MODE = 'SHOW_MODE';

export const CURRENT_USER_PROFILE_LOAD = 'CURRENT_USER_PROFILE_LOAD';

export const SET_CURRENT_MENU_ITEM = 'SET_CURRENT_MENU_ITEM';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
