export const LOAD_AUTHOR_PROFILE_STARTED = 'LOAD_AUTHOR_PROFILE_STARTED';
export const LOAD_AUTHOR_PROFILE__SUCCESS = 'LOAD_AUTHOR_PROFILE_SUCCESS';
export const LOAD_AUTHOR_PROFILE__FAILURE = 'LOAD_AUTHOR_PROFILE_FAILURE';
