export const SET_ARTICLES = 'SET_ARTICLES';
export const SET_FILTER_BY_AUTHOR = 'SET_FILTER_BY_AUTHOR';

export const LOAD_ARTICLES_REQUEST = 'LOAD_ARTICLES_REQUEST';
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
export const LOAD_ARTICLES_FAILURE = 'LOAD_ARTICLES_FAILURE';
