export const SET_ARTICLES = 'SET_ARTICLES';
export const UPDATE_LIST_ARTICLES = 'UPDATE_LIST_ARTICLES';
export const SET_FILTER_BY_AUTHOR = 'SET_FILTER_BY_AUTHOR';

export const LOAD_ARTICLES_STARTED = 'LOAD_ARTICLES_STARTED';
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
export const LOAD_ARTICLES_FAILURE = 'LOAD_ARTICLES_FAILURE';
